/* =============================================================
   ERSeP · Electricistas habilitados
   Zonificación de las localidades del Registro (sistema Volta)
   y mapa esquemático de la Provincia de Córdoba.
   ============================================================= */
window.ZONAS = {
  capital: {
    nombre: 'Córdoba Capital',
    color: '#b51234',
    localidades: ['CORDOBA', 'C?RDOBA', 'CORDOBA CAPITAL', 'CAPITAL', 'ARGUELLO', 'ARGUELLO CBA',
      'CORDOBA ARGUELLO', 'GUI?AZU', 'VILLA LOS PINOS - CORDOBA CAPITAL.', 'VILLA SAN NICOLAS',
      'SAN NICOLAS', 'MEDIA NARANJA']
  },
  granCordoba: {
    nombre: 'Gran Córdoba',
    color: '#0f4c8a',
    localidades: ['LA CALERA', 'MALAGUE?O', 'MALAGUENO', 'SALDAN', 'VILLA ALLENDE', 'MENDIOLAZA',
      'UNQUILLO', 'RIO CEBALLOS', 'SALSIPUEDES', 'AGUA DE ORO', 'EL MANZANO', 'LA GRANJA',
                  'TOLEDO', 'BOUWER', 'LOZADA', 'LOZADA Dpto SANTA MARIA', 'DIQUE CHICO',
      'MONTE RALO', 'DESPE?ADEROS', 'DESPENADEROS', 'DESPE?ADERO', 'VILLA PARQUE SANTA ANA',
      'PARQUE SANTA ANA', 'FALDA DEL CARMEN', 'ALTA GRACIA', 'ANISACATE', 'VILLA ANIZACATE',
      'VALLE DE ANISACATE', 'LA BOLSA', 'VILLA LA BOLSA', 'LA PAISANITA', 'LA RANCHERITA',
      'LOS CEDROS', 'VILLA LOS AROMOS', 'VILLA LOS AROMOS, CORDOBA', 'VILLA DEL PRADO',
      'SAN ANTONIO DE ARRED.', 'SAN ANTONIO DE ARREDONDO', 'MAYU SUMAJ', 'ICHO CRUZ',
      'VILLA RIO ICHO CRUZ', 'VILLA ICHO CRUZ CORDOBA', 'CUESTA BLANCA', 'SAN CLEMENTE',
      'POTRERO DE GARAY', 'LA SERRANITA', 'VILLA CIUDAD AMERICA', 'VILLAS CIUDAD DE AMERICA',
      'VILLA SANTA CRUZ DEL LAGO', 'ESTANCIA VIEJA', 'SAN ROQUE', 'COMUNA SAN ROQUE',
      'SANTA MARIA',
      'SANTA ANA (DPTO STA MARIA)',                         ]
  },
  punilla: {
    nombre: 'Punilla y Sierras',
    color: '#079ed0',
    localidades: ['VILLA CARLOS PAZ', 'TANTI', 'BIALET MASSE', 'SANTA MARIA DE PUNILLA',
      'SANTA MAR?A DE PUNILLA', 'COSQUIN', 'MOLINARI', 'VALLE HERMOSO', 'LA FALDA',
      'HUERTA GRANDE', 'VILLA GIARDINO', 'LA CUMBRE', 'CAPILLA DEL MONTE', 'LOS COCOS',
      'CHARBONIER', 'SAN ESTEBAN', 'CASA GRANDE', 'VILLA PARQUE SIQUIMAN', 'PARQUE SIQUIMAN',
      'VILLA CA?ADA DEL SAUCE', 'SAUCE ARRIBA', 'CRUZ DE CA?A', 'SAN MARCOS SIERRA',
      'SAN MARCOS SIERRAS', 'CHU?A', 'PUNILLA', 'VILLA CERRO AZUL', 'LAS RABONAS']
  },
  calamuchita: {
    nombre: 'Calamuchita',
    color: '#48a62f',
    localidades: ['VILLA GENERAL BELGRANO', 'SANTA ROSA DE CALAMUCHITA', 'SANTA ROSA DE CALAM.',
      'VILLA RUMIPAL', 'VILLA DEL DIQUE', 'EMBALSE', 'EMBALSE DE CALAMUCHITA',
      'EMBALSE DE RIO TERCERO', 'LOS REARTES', 'VILLA C PQUE LOS REARTES',
      'VILLA CIUDAD PARQUE LOS REARTES', 'VILLA PARQUE LOS REARTES', 'LA CUMBRECITA',
      'YACANTO', 'VILLA YACANTO', 'VILLA AMANCAY', 'SAN IGNACIO DE CALAMUCHITA', 'AMBOY',
      'SANTA MONICA', 'LOS MOLINOS', 'LOS CONDORES', 'CALAMUCHITA LOS CONDORES', 'CALAMUCHICA',
      'RIO DE LOS SAUCES', 'ELENA', 'SAN AGUSTIN', 'LA CRUZ', 'SANTA ROSA',
      'RIO TERCERO', 'RIO TERCERO, CORDOBA', 'ALMAFUERTE', 'CORRALITO', 'TANCACHA',
      'VILLA ASCASUBI', 'PAMPAYASTA SUD', 'DALMACIO VELEZ', 'DALMACIO VELEZ SARSFIELD',
      'HERNANDO', 'LAS ISLETILLAS', 'JAMES CRAIK', 'OLIVA', 'COLONIA ALMADA', 'TICINO',
      'GENERAL FOTHERINGHAM', 'LOS ZORROS', 'PUESTO DE CASTRO', 'INTIYACO', 'EL BRETE']
  },
  traslasierra: {
    nombre: 'Traslasierra y Oeste',
    color: '#eead08',
    localidades: ['VILLA DOLORES', 'VILLA DLORES', 'MINA CLAVERO', 'VILLA CURA BROCHERO',
      'NONO', 'LAS CALLES', 'LAS TAPIAS', 'LAS CHACRAS', 'LOS HORNILLOS', 'LA POBLACION',
      'LUYABA', 'SAN JAVIER', 'SAN JAVIER Y YACANTO', 'VILLA DE LAS ROSAS', 'LOS CERRILLOS',
      'PANAHOLMA', 'AMBUL', 'SALSACATE', 'SAN CARLOS MINAS', 'ARROYO DE LOS PATOS',
      'VILLA SARMIENTO', 'SARMIENTO', 'LA PAZ', 'QUEBRADA DE LOS POZOS', 'EL FUERTE',
      'VILLA ROSSI', 'TOSQUITA']
  },
  norte: {
    nombre: 'Norte y Noroeste',
    color: '#a88976',
    localidades: ['CRUZ DEL EJE', 'VILLA DE SOTO', 'SERREZUELA', 'DEAN FUNES', 'QUILINO',
      'VILLA DEL TOTORAL', 'TOTORAL', 'SINSACATE', 'JESUS MARIA', 'COLONIA CAROYA',
      'COLONIA VICENTE AG?ERO', 'VILLA TULUMBA', 'SAN JOSE DE LA DORMIDA', 'LUCIO V MANSILLA',
      'SAN JOSE DE LAS SALINAS', 'SAN FRANCISCO DEL CHA?AR', 'SAN FRANCISCO DEL CHANAR',
      'VILLA DE MARIA', 'VILLA DE MARIA DEL RIO SECO', 'SEBASTIAN ELCANO', 'LAS ARRIAS',
      'CA?ADA DE LUQUE', 'CANADA DE LUQUE', 'OBISPO TREJO', 'LA PARA', 'LA PUERTA', 'MARULL', 'BALNEARIA',
      'MIRAMAR', 'MIRAMAR ANSENUZA', 'ALTOS DE CHIPION', 'LA TORDILLA', 'TORO PUJIO',
      'SANTA CATALINA', 'LA PAMPA', 'KILOMETRO 658', 'LAS PICHANAS', 'COLONIA LAS PICHANAS',
      'NICOLAS BRUZONE']
  },
  este: {
    nombre: 'Este y Sudeste',
    color: '#0c6858',
    localidades: ['LAS JUNTURAS', 'PIQUILLIN', 'CAPILLA DE REMEDIOS', 'RIO SEGUNDO', 'PILAR', 'COSTA SACATE', 'SANTA ROSA DE RIO PRIMERO', 'RIO PRIMERO', 'VILLA SANTA ROSA', 'PACHECO DE MELO', 'CAPILLA DEL CARMEN', 'MATORRALES', 'VILLA DEL ROSARIO', 'LAGUNA LARGA', 'MANFREDI', 'ONCATIVO', 'IMPIRA', 'LUQUE', 'SANTIAGO TEMPLE', 'CALCHIN', 'CALCHIN OESTE', 'COLAZO', 'LAS JUNTURAS', 'MONTE CRISTO', 'MONTECRISTO', 'MALVINAS ARGENTINAS', 'COMUNA MALVINAS ARGENTINAS', 'ESTACION GENERAL PAZ', 'COLONIA TIROLESA', 'MI GRANJA', 'ESTACION JUAREZ CELMAN', 'JUAREZ CELMAN', 'MI VALLE', 'SAN FRANCISCO', 'MORTEROS', 'BRINKMANN', 'PORTE?A', 'PORTENA', 'FREYRE',
      'DEVOTO', 'SEEBER', 'COLONIA VIGNAUD', 'LA PAQUITA', 'COLONIA MARINA', 'ALICIA',
      'LAS VARILLAS', 'LAS VARAS', 'SACANTA', 'EL TIO', 'VILLA CONCEPCION DEL TIO',
      'ARROYITO', 'TRANSITO', 'VILLA DEL TRANSITO', 'COLONIA SAN BARTOLOME', 'EL ARA?ADO',
      'EL ARANADO', 'SATURNINO MARIA LASPIUR', 'COLONIA ITALIANA', 'BELL VILLE',
      'MARCOS JUAREZ', 'MARCOS JU?REZ', 'LEONES', 'CORRAL DE BUSTOS',
      'CORRAL DE BUSTOS IFFLINGER', 'CORRAL DE BUSTOS IFFLINGER IFFLINGER', 'CAMILO ALDAO',
      'ISLA VERDE', 'INRIVILLE', 'MONTE BUEY', 'JUSTINIANO POSSE', 'ORDO?EZ', 'IDIAZABAL',
      'PASCANAS', 'LABORDE', 'MONTE MAIZ', 'CRUZ ALTA', 'SAIRA', 'CINTRA', 'NOETINGER',
      'CAVANAGH', 'GUATIMOZIN', 'ALEJO LEDESMA', 'BENJAMIN GOULD', 'ARIAS', 'CANALS',
      'SILVIO PELLICO', 'BALLESTEROS', 'BALLESTEROS SUD', 'MORRISON', 'SAN MARCOS SUD',
      'SAN ANTONIO DE LITIN', 'PUEBLO ITALIANO', 'WENCESLAO ESCALANTE', 'VIAMONTE',
      'MONTE DE LOS GAUCHOS', 'ROSARIO DEL SALADILLO', 'VILLA MARIA', 'VILLA MAR?A',
      'VILLA MARA', 'VILLA NUEVA', 'TIO PUJIO', 'ARROYO CABRAL', 'ARROYO ALGODON',
      'LA PLAYOSA', 'LA PALESTINA', 'AUSONIA', 'ETRURIA', 'LA LAGUNA', 'CHAZON',
      'POZO DEL MOLLE', 'CARRILOBO', 'LUCA', 'GENERAL ROCA', 'LOS SURGENTES']
  },
  sur: {
    nombre: 'Sur y Sudoeste',
    color: '#75828a',
    localidades: ['RIO CUARTO', 'R?O CUARTO', 'LAS HIGUERAS', 'HOLMBERG', 'SANTA CATALINA HOLMBERG',
      'SANTA CATALINA Y HOLMBERG', 'CORONEL MOLDES', 'CORONEL BAIGORRIA', 'SAMPACHO',
      'ALCIRA', 'ALCIRA GIGENA', 'BERROTARAN', 'LAS PE?AS', 'LAS ACEQUIAS', 'LAS PERDICES',
      'GENERAL DEHEZA', 'GENERAL CABRERA', 'CARNERILLO', 'REDUCCION', 'OLAETA', 'CHARRAS',
      'BENGOLEA', 'UCACHA', 'SAN BASILIO', 'LA CARLOTA', 'ALEJANDRO ROCA', 'SANTA EUFEMIA',
      'LOS CISNES', 'LA CESIRA', 'SERRANO', 'MELO', 'LABOULAYE', 'GENERAL LEVALLE',
      'GENERAL LAVALLE', 'RIO BAMBA', 'BUCHARDO', 'HUINCA RENANCO', 'VILLA HUIDOBRO',
      'VILLA VALERIA', 'ITALO', 'MATTALDI', 'JOVITA', 'SANTA MAGDALENA', 'DEL CAMPILLO',
      'VICU?A MACKENNA', 'ADELIA MARIA', 'LAS VERTIENTES', 'CHAJAN', 'SUCO', 'ACHIRAS',
      'LAS ALBAHACAS', 'ALPA CORRAL', 'BULNES', 'HUANCHILLA', 'PINCEN', 'PASCO',
      'LOS ROBLES', 'LA POSTA', 'LA FRANCIA', 'ARROYO SAN ANTONIO', 'ALTO ALEGRE',
      'MONTE LE?A', 'AVELLANEDA', 'SAN JOAQUIN', 'SAN PEDRO', 'SAN LORENZO',
      'SAN JOSE DE LA QUINTANA', 'LA CAUTIVA']
  },
  otras: {
    nombre: 'Otras / sin zona',
    color: '#858585',
    localidades: ['SIN LOCALIDAD', 'CABA', 'ROSARIO', 'MOISES VILLE', 'COMODORO RIVADAVIA',
      'EL BOLSON', 'SANTA FE']
  }
};
