const API=(window.ESTADISTICAS_API_BASE||"").replace(/\/$/,"");
const $=id=>document.getElementById(id);
let meta=null; let currentTsv=""; let allSeries=[];
function message(text,type="ok",id="msg"){const el=$(id);if(!el)return;el.textContent=text;el.className=`stats-message ${type}`}
function clearMessage(id="msg"){const el=$(id);if(!el)return;el.textContent="";el.className="stats-message"}
async function request(path,opts={}){const res=await fetch(`${API}${path}`,opts);let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.detail||`Error ${res.status}`);return data}
function renderSeries(list){const sel=$("series");const selected=new Set([...sel.selectedOptions].map(o=>o.value));sel.innerHTML="";for(const item of list){const o=document.createElement("option");o.value=item.id;o.textContent=item.name;o.selected=selected.has(item.id);sel.appendChild(o)}}
function renderDates(values){for(const id of ["desde","hasta"]){$(id).innerHTML="";for(const x of values){const o=document.createElement("option");o.value=x.value;o.textContent=x.label;$(id).appendChild(o)}}if(values.length){$("desde").selectedIndex=0;$("hasta").selectedIndex=values.length-1}}
async function loadMeta(){if(!API){message("Falta configurar la URL de API_Estadisticas en config.js.","error");return}message("Cargando indicadores…","ok");try{meta=await request("/api/meta");allSeries=meta.value_columns||[];renderSeries(allSeries);renderDates(meta.index_values||[]);clearMessage()}catch(e){message(e.message,"error")}}
function selectedSeries(){return [...$("series").selectedOptions].map(o=>o.value)}
function params(){const cols=selectedSeries();if(!cols.length)throw new Error("Seleccioná al menos una serie.");return new URLSearchParams({col_idxs:cols.join(","),desde:$("desde").value,hasta:$("hasta").value})}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function renderTable(headers,rows){$("thead").innerHTML=headers.map(h=>`<th>${esc(h)}</th>`).join("");$("tbody").innerHTML=rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join("")}</tr>`).join("")}
function updateKpis(cols,rows){$("k_series").textContent=cols.length;$("k_periodos").textContent=rows.length;$("k_desde").textContent=$("desde").selectedOptions[0]?.textContent||"—";$("k_hasta").textContent=$("hasta").selectedOptions[0]?.textContent||"—"}
async function renderChart(){const p=params();const data=await request(`/api/series?${p}`);const traces=(data.series||[]).map(s=>({x:data.dates,y:s.values,name:s.col,type:"scatter",mode:"lines+markers"}));Plotly.newPlot("chart",traces,{margin:{l:56,r:20,t:15,b:55},legend:{orientation:"h"},hovermode:"x unified",paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)"},{responsive:true,displaylogo:false})}
async function consultar(){clearMessage();try{const p=params(),cols=selectedSeries();message("Consultando datos…","ok");const data=await request(`/api/data?${p}`);currentTsv=data.tsv||"";renderTable(data.headers||[],data.rows||[]);updateKpis(cols,data.rows||[]);$("resultados").hidden=false;$("copiar").disabled=!currentTsv;$("table_title").textContent="Datos consultados";await renderChart();clearMessage()}catch(e){message(e.message,"error")}}
async function variaciones(){clearMessage();try{const p=params(),cols=selectedSeries();message("Calculando variaciones…","ok");const data=await request(`/api/variaciones?${p}`);const headers=["Índice","Valor inicial","Valor final","Variación %"];const rows=(data.data||[]).map(x=>[x.serie,x.inicial??"",x.final??"",x.variacion==null?"":x.variacion.toFixed(2)]);renderTable(headers,rows);currentTsv=[headers,...rows].map(r=>r.join("\t")).join("\r\n");updateKpis(cols,rows);$("resultados").hidden=false;$("copiar").disabled=!currentTsv;$("table_title").textContent="Variaciones punta a punta";await renderChart();clearMessage()}catch(e){message(e.message,"error")}}
async function copiar(){if(!currentTsv)return;try{await navigator.clipboard.writeText(currentTsv);message("Tabla copiada. Ya podés pegarla en Excel.","ok")}catch{message("El navegador no permitió copiar al portapapeles.","error")}}
function limpiar(){[...$("series").options].forEach(o=>o.selected=false);$("search").value="";renderSeries(allSeries);$("resultados").hidden=true;currentTsv="";$("copiar").disabled=true;clearMessage();Plotly.purge("chart")}
$("consultar").onclick=consultar;$("variaciones").onclick=variaciones;$("copiar").onclick=copiar;$("limpiar").onclick=limpiar;$("search").addEventListener("input",e=>{const q=e.target.value.trim().toLowerCase();renderSeries(allSeries.filter(x=>x.name.toLowerCase().includes(q)))});
loadMeta();
